export const newAdditionList = [
  {
    id: "1",
    name: "Jerky persimmon",
    category: "dried fruits",
    form: "prepackaged", // 'on weight
    // initialVolume: "1",
    increaseVolume: "0.5",
    measure: "kg",
    onSale: true,
    price: "8.6",
    oldPrice: "9.0",
    currency: "$",
    imgPath: "/fakeImages/Jerky_persimmon.png",
    rating: "4.8",
  },
  {
    id: "2",
    name: "Macadamia in the shell",
    category: "dried fruits",
    form: "prepackaged", // 'on weight
    // initialVolume: "2",
    increaseVolume: "0.5",
    measure: "kg",
    price: "28",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
    rating: "4.8",
  },
  {
    id: "3",
    name: "Spiced nuts",
    category: "nuts",
    form: "on weight",
    // initialVolume: "500",
    increaseVolume: "100",
    measure: "g",
    price: "17.2",
    oldPrice: "29",
    onSale: true,
    currency: "$",
    imgPath: "/fakeImages/Spiced_nuts.png",
    rating: "4.5",
  },
  {
    id: "4",
    name: "Banana",
    category: "fruits",
    form: "on weight",
    // initialVolume: "4",
    increaseVolume: "0.5",
    measure: "kg",
    price: "5.7",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Banana.png",
    rating: "5",
  },
  {
    id: "5",
    name: "Premium kiwifruit",
    category: "fruits",
    form: "on weight",
    // initialVolume: "3",
    increaseVolume: "0.5",
    measure: "kg",
    price: "15.5",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/kiwifruit.png",
    rating: "4.3",
  },
  {
    id: "6",
    name: "Jerky persimmon two",
    category: "dried fruits",
    form: "on weight",
    // initialVolume: "1",
    increaseVolume: "0.5",
    measure: "kg",
    price: "38.6",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Jerky_persimmon.png",
    rating: "4.8",
  },
  {
    id: "7",
    name: "Macadamia in the shell two",
    category: "nuts",
    form: "on weight",
    // initialVolume: "2",
    increaseVolume: "0.5",
    measure: "kg",
    price: "43",
    oldPrice: "49",
    onSale: true,
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
    rating: "4.8",
  },
  {
    id: "8",
    name: "Spiced nuts two",
    category: "nuts",
    form: "on weight",
    // initialVolume: "500",
    increaseVolume: "100",
    measure: "g",
    price: "21.2",
    oldPrice: "28",
    onSale: true,
    currency: "$",
    imgPath: "/fakeImages/Spiced_nuts.png",
    rating: "4.8",
  },
  {
    id: "9",
    name: "Banana two",
    category: "fruits",
    form: "on weight",
    // initialVolume: "4",
    increaseVolume: "0.5",
    measure: "kg",
    price: "12.7",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Banana.png",
    rating: "4.3",
  },
  {
    id: "10",
    name: "Macadamia",
    category: "nuts",
    form: "prepackaged", // 'on weight
    // initialVolume: "2",
    increaseVolume: "0.5",
    measure: "kg",
    price: "37",
    oldPrice: "45",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
    rating: "4.1",
  },
  {
    id: "11",
    name: "Chestnut",
    category: "nuts",
    form: "prepackaged", // 'on weight
    // initialVolume: "2",
    increaseVolume: "0.5",
    measure: "kg",
    price: "19",
    oldPrice: "25",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
    rating: "4.1",
  },
];
