import { ICartCardData } from "types/types";

export const cartData: ICartCardData[] = [
  {
    id: "1",
    name: "Jerky persimmon",
    value: "1",
    increaseVolume: ".5",
    unit: "kg",
    price: "8.6",
    currency: "$",
    imgPath: "/fakeImages/Jerky_persimmon.png",
  },
  {
    id: "2",
    name: "Macadamia in the shell",
    value: "2",
    increaseVolume: "0.5",
    unit: "kg",
    price: "28",
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
  },
  {
    id: "3",
    name: "Spiced nuts",
    value: "500",
    increaseVolume: "100",
    unit: "g",
    price: "7.2",
    currency: "$",
    imgPath: "/fakeImages/Spiced_nuts.png",
  },
  {
    id: "4",
    name: "Banana",
    value: "4",
    increaseVolume: "0.5",
    unit: "kg",
    price: "5.7",
    currency: "$",
    imgPath: "/fakeImages/Banana.png",
  },
  {
    id: "5",
    name: "Premium kiwifruit",
    value: "3",
    increaseVolume: "0.5",
    unit: "kg",
    price: "15.5",
    currency: "$",
    imgPath: "/fakeImages/kiwifruit.png",
  },
  {
    id: "6",
    name: "Jerky persimmon two",
    value: "1",
    increaseVolume: "0.5",
    unit: "kg",
    price: "8.6",
    currency: "$",
    imgPath: "/fakeImages/Jerky_persimmon.png",
  },
  {
    id: "7",
    name: "Macadamia in the shell two",
    value: "2",
    increaseVolume: "0.5",
    unit: "kg",
    price: "28",
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
  },
  {
    id: "8",
    name: "Spiced nuts two",
    value: "500",
    increaseVolume: "100",
    unit: "g",
    price: "7.2",
    currency: "$",
    imgPath: "/fakeImages/Spiced_nuts.png",
  },
  {
    id: "9",
    name: "Banana two",
    value: "4",
    increaseVolume: "0.5",
    unit: "kg",
    price: "5.7",
    currency: "$",
    imgPath: "/fakeImages/Banana.png",
  },
];
