export const listsData = [
  {
    id: "1",
    name: "Jerky persimmon",
    // initialVolume: "1",
    // increaseVolume: ".5",
    // unit: "kg",
    onSale: true,
    price: "8.6",
    oldPrice: "9.0",
    currency: "$",
    imgPath: "/fakeImages/Jerky_persimmon.png",
    rating: "4.8",
  },
  {
    id: "2",
    name: "Macadamia in the shell",
    // initialVolume: "2",
    // increaseVolume: "0.5",
    unit: "kg",
    price: "28",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
    rating: "4.8",
  },
  {
    id: "3",
    name: "Spiced nuts",
    // initialVolume: "500",
    // increaseVolume: "100",
    unit: "g",
    price: "7.2",
    oldPrice: "",
    onSale: true,
    currency: "$",
    imgPath: "/fakeImages/Spiced_nuts.png",
    rating: "4.5",
  },
  {
    id: "4",
    name: "Banana",
    // initialVolume: "4",
    // increaseVolume: "0.5",
    unit: "kg",
    price: "5.7",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Banana.png",
    rating: "5",
  },
  {
    id: "5",
    name: "Premium kiwifruit",
    // initialVolume: "3",
    // increaseVolume: "0.5",
    unit: "kg",
    price: "15.5",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/kiwifruit.png",
    rating: "4.3",
  },
  {
    id: "6",
    name: "Jerky persimmon two",
    // initialVolume: "1",
    // increaseVolume: "0.5",
    unit: "kg",
    price: "8.6",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Jerky_persimmon.png",
    rating: "4.8",
  },
  {
    id: "7",
    name: "Macadamia in the shell two",
    // initialVolume: "2",
    // increaseVolume: "0.5",
    unit: "kg",
    price: "28",
    oldPrice: "30",
    onSale: true,
    currency: "$",
    imgPath: "/fakeImages/Macadamia.png",
    rating: "4.8",
  },
  {
    id: "8",
    name: "Spiced nuts two",
    // initialVolume: "500",
    // increaseVolume: "100",
    // unit: "g",
    price: "7.2",
    oldPrice: "8",
    onSale: true,
    currency: "$",
    imgPath: "/fakeImages/Spiced_nuts.png",
    rating: "4.8",
  },
  {
    id: "9",
    name: "Banana two",
    // initialVolume: "4",
    // increaseVolume: "0.5",
    // unit: "kg",
    price: "5.7",
    oldPrice: "",
    onSale: false,
    currency: "$",
    imgPath: "/fakeImages/Banana.png",
    rating: "4.3",
  },
];
