export const data = [
  {
    id: "1",
    name: "Jerky persimmon",
    volume: "1",
    unit: "kg",
    price: "8.6",
    currency: "$",
    img: "./fakeImages/Jerky_persimmon.png",
  },
  {
    id: "2",
    name: "Macadamia in the shell",
    volume: "2",
    unit: "kg",
    price: "28",
    currency: "$",
    img: "./fakeImages/Macadamia.png",
  },
  {
    id: "3",
    name: "Spiced nuts",
    volume: "500",
    unit: "g",
    price: "7.2",
    currency: "$",
    img: "./fakeImages/Spiced_nuts.png",
  },
  {
    id: "4",
    name: "Banana",
    volume: "4",
    unit: "kg",
    price: "5.7",
    currency: "$",
    img: "./fakeImages/Banana.png",
  },
  {
    id: "5",
    name: "Premium kiwifruit",
    volume: "3",
    unit: "kg",
    price: "15.5",
    currency: "$",
    img: "./fakeImages/kiwifruit.png",
  },
  {
    id: "6",
    name: "Jerky persimmon two",
    volume: "1",
    unit: "kg",
    price: "8.6",
    currency: "$",
    img: "./fakeImages/Jerky_persimmon.png",
  },
  {
    id: "7",
    name: "Macadamia in the shell two",
    volume: "2",
    unit: "kg",
    price: "28",
    currency: "$",
    img: "./fakeImages/Macadamia.png",
  },
  {
    id: "8",
    name: "Spiced nuts two",
    volume: "500",
    unit: "g",
    price: "7.2",
    currency: "$",
    img: "./fakeImages/Spiced_nuts.png",
  },
  {
    id: "9",
    name: "Banana two",
    volume: "4",
    unit: "kg",
    price: "5.7",
    currency: "$",
    img: "./fakeImages/Banana.png",
  },
];
