import ButtonExamples from "components/UIkit/Button/ButtonExamples";
import Search from "components/UIkit/Search";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Eco Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <section>Home</section>
    </>
  );
};

export default Home;
