import Head from "next/head";
import ButtonExamples from "../components/UIkit/Button/ButtonExamples";
import Checkbox from "components/UIkit/Checkbox";
import Box from "components/Box";
import CartCard from "components/CartCard";
import SearchExamples from "components/UIkit/Search/SearchExamples";
import FieldExamples from "components/UIkit/Field/FieldExamples";
import { FC, useState } from "react";
import SubscribeInputExamples from "components/UIkit/SubscribeInput/SubscribeInputExamples";
import SelectExamples from "components/UIkit/Select/SelectExamples";
// import ProductItem from "components/ProductItem";
import ModalExamples from "components/UIkit/Modal/ModalExamples";
import Section from "components/Section";
import Cart from "components/Cart";
import ProductList from "components/ProductList";
import PriceRange from "components/UIkit/PriceRange";
import ReviewsRangeExample from "components/UIkit/ReviewsRange/ReviewsRangeExample";

export async function getStaticProps() {
  // const response = await axios.get(
  //   "http://localhost:3000/_next/data/development/1/2.json?productCatalogId=1&productId=2"
  // );

  // return { props: { data: response.data } };

  return { props: {} };
}

interface ITestProps {}

const Test: FC<ITestProps> = () => {
  return (
    <>
      <Head>
        <title>Eco Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <h1>TITLE TEST</h1>
      {/* <Section> */}
      {/* <ReviewsRangeExample /> */}
      {/* <ModalExamples /> */}
      {/* <SelectExamples /> */}
      {/* <SubscribeInputExamples /> */}
      {/* <FieldExamples /> */}
      {/* <SearchExamples /> */}
      {/* <ButtonExamples /> */}
      {/* </Section> */}
    </>
  );
};

export default Test;
