import Head from "next/head";
import ButtonExamples from "../components/UIkit/Button/ButtonExamples";
import ProductCard from "components/ProductCard";
import Checkbox from "components/UIkit/Checkbox";
import Box from "components/Box";
import CartCard from "components/CartCard";
import Search from "components/UIkit/Search";

const Test = () => {
  return (
    <>
      <Head>
        <title>Eco Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section>
        Home
        {/* <ButtonExamples /> */}
        {/* Search */}
        <Box p="30px" backgroundColor="#c7701f">
          <Search
            fontSize="s"
            borderStyle="none"
            pr="50px"
            onSearch={console.log}
          />
        </Box>
        <Box p="30px" backgroundColor="white">
          <Search
            fontSize="s"
            borderStyle="solid"
            borderColor="accent"
            width="400px"
          />
        </Box>
        {/* Search */}
        {/* <Box
          display="flex"
          flexDirection="column"
          justifyContent="center"
          padding="20px"
          gridGap="40px"
        >
          <ProductCard />
          <ProductCard onSale={true} />
          <CartCard />
        </Box>
        <Box padding="20px">
          <Checkbox />
          <Checkbox label="checkbox with label" />
        </Box> */}
      </section>
    </>
  );
};

export default Test;
