import Head from "next/head";
import ButtonExamples from "../components/UIkit/Button/ButtonExamples";

const Home = () => {
  return (
    <>
      <Head>
        <title>Eco Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section>
        Home
        <ButtonExamples />
      </section>
    </>
  );
};

export default Home;
